public  class Exception {
//    public static void main(String[] args) {
//        a();
//    }
//    public static  void a(){
//        try {
//            b();
//        }
//        catch(ArithmeticException e) {
//
//            System.out.println(e);
//
//        }
//
//    }
//    public static  void b() throws ArithmeticException{
//        int num1=10;
//        int num2=0;
//        System.out.println(num1/num2);
//    }

}
